### ISSUE TITLE
New server TODO

### ISSUE THREAD

**Issue by benjaoming** [migcontrol/django-migcontrol#195]
* [x] Create new "production" server
* [x] Update DNS for domain
* [x] Update configuration of mail server
* [x] Shut down old test server

**Comment by shavek** [comment]
You just let me know here what I can do, if anything :)

**Comment by benjaoming** [comment]
All done here :)
